#
###################################
# Site wide configuration
####################################
#
title: George Lukas
email: # david.whipp@helsinki.fi
description: George Lukas's personal website
url: https://z0del.github.io # the base hostname & protocol for your site


#
###################################
# Jekyll configuration
####################################
#
timezone:          Europe/Helsinki
markdown:          kramdown
highlighter:       rouge
excerpt_separator: <!--more-->
permalink:         /articles/:year-:month/:title

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  enable_coderay: false

#
###################################
# Site Owner configuration
####################################
#
owner:
  name: George Lukas
  avatar: # Whipp-circle.png
  job: # "Computers, rocks, and beer"
  bio: # "Professor of Geodynamic Modelling at the University of Helsinki, Finland."
  email: # david.whipp@helsinki.fi
  disqus-shortname:
  twitter: # dave_whipp
  facebook: #username
  google:
    plus: #username
    analytics: # UA-41847639-2
    verify:
    ad-client:
    ad-slot:
  bing-verify:
  github: z0del
  gitlab: #username
  stackoverflow: #123456/username   from a "http://stackoverflow.com/users/123456/username" link
  linkedin: # dwhipp #username
  skype: #username
  xing: #username
  instagram: #username
  lastfm: #username
  tumblr: #username
  pinterest: #username
  foursquare: #username
  steam: #username
  dribbble: #username
  youtube: #username
  youtubec: UCIvX6ZFgUP5DgvBSomhz-yw #username
  soundcloud: #username
  weibo: #username
  flickr: #username
  500px: #username
  codepen: #username
